export const GET_MACHINE_INITIATED = "GET_MACHINE_INITIATED";
export const GET_MACHINE_SUCCESS = "GET_MACHINE_SUCCESS";
export const GET_MACHINE_ERROR = "GET_MACHINE_ERROR";



export const POST_MACHINE_INITIATED = "POST_MACHINE_INITIATED";
export const POST_MACHINE_SUCCESS = "POST_MACHINE_SUCCESS";
export const POST_MACHINE_ERROR = "POST_MACHINE_ERROR";