export const GET_HEADQUATER_INITIATED = "GET_HEADQUATER_INITIATED";
export const GET_HEADQUATER_SUCCESS = "GET_HEADQUATER_SUCCESS";
export const GET_HEADQUATER_ERROR = "GET_HEADQUATER_ERROR";


export const POST_HEADQUATER_INITIATED = "POST_HEADQUATER_INITIATED";
export const POST_HEADQUATER_SUCCESS = "POST_HEADQUATER_SUCCESS";
export const POST_HEADQUATER_ERROR = "POST_HEADQUATER_ERROR";
